// Generated by CoffeeScript 1.6.2
(function() {
  var field, fields, fieldset, _i, _len;

  this.fieldsets = {
    top: [
      {
        name: 'product',
        label: 'Vara/Þjónusta',
        input: true
      }, {
        name: 'company',
        label: 'Fyrirtæki',
        input: true
      }
    ],
    topSmall: [
      {
        name: 'connection',
        label: 'Tengill',
        input: true
      }, {
        name: 'accepted',
        label: 'Samþykkt',
        input: true
      }, {
        name: 'team',
        label: 'Teymi',
        input: true
      }, {
        name: 'created',
        label: 'Afhending',
        input: true
      }
    ],
    main: [
      {
        name: 'background',
        n: 1,
        label: 'SKILGREINING VERKEFNIS',
        icon: true,
        placeholder: '- Lýsing á verkefninu\n– Bakgrunnur vörunnar / þjónustunnar'
      }, {
        name: 'competition',
        n: 2,
        label: 'SAMKEPPNI',
        icon: true,
        placeholder: 'Staða vörunnar á markaðinum í samanburði við samkeppnisaðila',
        popupPosition: 'left'
      }, {
        name: 'goals',
        n: 3,
        label: 'MARKMIÐ',
        icon: true,
        placeholder: '- Hver mun markaðsstaðan verða eftir auglýsingaherferðina?\n- Hvaða áhrif hafa auglýsingarnar á ímynd fyrirtækisins?\n- Hvað viljum við að fólk hugsi þegar það sér auglýsingarnar og hvað viljum við að það geri?',
        popupPosition: 'left'
      }, {
        name: 'promise',
        n: 4,
        label: 'LOFORÐIÐ',
        icon: true,
        placeholder: 'Hvað er það mikilvægasta sem markhópurinn þarf að vita um\n vöruna, þjónustuna eða fyrirtækið? Hvaða staðreyndir styðja\n loforðið.<br><br>\n\n Eitt loforð = Ein setning'
      }, {
        name: 'focusgroup',
        n: 5,
        label: 'MARKHÓPUR',
        icon: true,
        placeholder: 'Það er engin ein rétt nálgun í því að skilgreina og kynna sér\n markhópinn. Hins vegar er mikilvægt að gögn séu skoðuð og\n markhópnum sé lýst á skýran hátt.<br><br>\n\n Hafa í huga að allir=enginn og jafnvel þótt markhópurinn sé\n mjög stór þá er alltaf hægt að skilgreina hann á einhvern hátt.\n <br><br>\n\n [Nánar í ítarefni]'
      }, {
        name: 'insight',
        n: 6,
        label: 'INNSÆI',
        icon: true,
        placeholder: 'Hvaða fullyrðingu um markhópinn, markaðinn, vöruna eða notkun á\n vörunni er hægt að vinna út frá? Hvaða tilfinning eða\n menningarfyrirbæri getur nýtst í herferðinni?'
      }, {
        name: 'strategy',
        n: 7,
        label: 'LYKILSPURNING',
        icon: true,
        placeholder: 'Spurning sem inniheldur lykilloforð og innsæi. Ein setning,\n í mesta lagi tvær.<br><br>\n\n Ef spurningin inniheldur „og/eða“ þá þarf að skipta henni upp í\n tvö brief. Annars er hún of löng og/eða óskýr.'
      }
    ],
    footer: [
      {
        name: 'media',
        label: 'Miðlar',
        placeholder: 'Hér þarf að kalla til samskiptavið og fá þeirra innsæi.'
      }, {
        name: 'progress',
        label: 'Árangursmæling',
        placeholder: 'Kaup, skráningar, eftirtekt. Mismunandi eftir verkefnum.'
      }, {
        name: 'other',
        label: 'Annað',
        placeholder: 'Budget. Tónn. Annað sem þarf að hafa í huga en kemur ekki fram\n annars staðar í briefi.'
      }
    ]
  };

  for (fieldset in fieldsets) {
    fields = fieldsets[fieldset];
    for (_i = 0, _len = fields.length; _i < _len; _i++) {
      field = fields[_i];
      field.about = Markdown[field.name] || '';
    }
  }

}).call(this);
